#' Add an info file to the project
#'
#' Function to create a file INFO.md.
#'
#' @param path The path to the main folder of the project
#' @param name The name of the project
#'
#' @return NULL invisibly
#'
#' @export
#'
add_info <- function(path, desc){

  header <- c(paste0("## ", desc), "\n")

  body <- c(
    "This project contains the following folders:",
    "\n",
    " * **Data**: raw data files.",
    " * **Data_Processed**: processed data files.",
    " * **Functions**: functions used in the project.",
    " * **Graphs**: all plots generated by the scripts.",
    " * **Reports**: Rmd files with reporting.",
    "\n",
    "<--- Here you can give a short summary of the project --->"
  )

  writeLines(c(header, body),
             con = file.path(path,"INFO.md"))
}